homework 34 solution
tkhambir/jv-internet-shop pull request #12
Opened 2020-09-29 13:44 UTC by tkhambir

2020-09-29 15:02 UTC, KostiantynVorobiov approved these changes
Все ОК!

2020-09-29 15:02 UTC, KostiantynVorobiov commented on src/main/java/com/internet/shop/util/HashUtil.java
> +    }
Насколько я понял из видео этого метода не нужно здесь писать

2020-09-29 16:19 UTC, KseniiaMakarova requested changes

2020-09-29 16:19 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/dao/jdbc/UserDaoJdbcImpl.java
>          user.setRoles(getRoles(id));
let's not set roles in this method
this creates a connection inside the connection

2020-09-29 16:19 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/util/HashUtil.java
> +    }
I agree, let's have this method as a private method in AuthenticationServiceImpl

2020-09-30 06:48 UTC, KseniiaMakarova approved these changes

2020-09-30 06:48 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/security/AuthenticationServiceImpl.java
> +    private static boolean isValid(String password, User user) {
```suggestion
    private boolean isValid(String password, User user) {
```

2020-10-16 14:34 UTC, merged